# Default values for helm-crate-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: salvner/crate-hello
  pullPolicy: IfNotPresent
  tag: "latest"

podAnnotations: {}
podLabels: {}

service:
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
