apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-crate-hello.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/instance: {{ include "helm-crate-hello.fullname" . }}
  type: ClusterIP