apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-crate-hello.fullname" . }}
  labels:
    {{- include "helm-crate-hello.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-crate-hello.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-crate-hello.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          livenessProbe:
            httpGet:
              path: /crate-hello
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /crate-hello
              port: {{ .Values.service.port }}
