apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.27
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80